<a href="https://colab.research.google.com/github/yuko23fukumoto/Emilee_AI_Academy_handson/blob/master/1_3_%E5%BF%9C%E7%94%A8%E6%95%B0%E5%AD%A6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 行列、固有値分解、特異値分解

行列種類
<img src="img/行列種類.jpg" width=60%/>

単位行列 \
単位行列はその対角成分に 1 が並び、他は全て 0 となる。
$$
\begin{align}
E &= \left(
    \begin{array}{ccc}
      1 & 0 & 0 \\
      0 & 1 & 0 \\
      0 & 0 & 1 \\
    \end{array}
  \right) \\
\end{align}
$$

行列Aと単位行列Eの積はAとなる。 \
AE=A

$$
\begin{align}
\left(
    \begin{array}{ccc}
      1 & 2 & 3 \\
      2 & 2 & 3 \\
      4 & 5 & 6 \\
    \end{array}
  \right) 
\left(
    \begin{array}{ccc}
      1 & 0 & 0 \\
      0 & 1 & 0 \\
      0 & 0 & 1 \\
    \end{array}
  \right)  =
\left(
    \begin{array}{ccc}
      1 & 2 & 3 \\
      2 & 2 & 3 \\
      4 & 5 & 6 \\
    \end{array}
  \right) 
\end{align}
$$

**行列の計算** \
行列の和
$$
\left[\begin{array}{c}
    a&b \\
    c&d \\
\end{array}\right] \quad
+
\left[\begin{array}{c}
    e&f \\
    g&h \\
\end{array}\right] \quad
=
\left[\begin{array}{c}
    a+e&b+f \\
    c+g&d+h \\
\end{array}\right] \quad
$$

行列の差
$$
\left[\begin{array}{c}
    a&b \\
    c&d \\
\end{array}\right] \quad
-
\left[\begin{array}{c}
    e&f \\
    g&h \\
\end{array}\right] \quad
=
\left[\begin{array}{c}
    a-e&b-f \\
    c-g&d-h \\
\end{array}\right] \quad
$$

数値と行列の積
$$
a*
\left[\begin{array}{c}
    x_{11}&x_{12} \\
    x_{21}&x_{22} \\
\end{array}\right] \quad
=
\left[\begin{array}{c}
    ax_{11}&ax_{12} \\
    ax_{21}&ax_{22} \\
\end{array}\right] \quad
$$

行列と行列の積
$$
\left[\begin{array}{c}
    a&b \\
    c&d \\
\end{array}\right] \quad
*
\left[\begin{array}{c}
    e&f \\
    g&h \\
\end{array}\right] \quad
=
\left[\begin{array}{c}
    ae+bg&af+bh \\
    ce+dg&cf+dh \\
\end{array}\right] \quad
$$

$$
\left[\begin{array}{c}
    x_{11}&x_{12}&x_{13} \\
    x_{21}&x_{22}&x_{23} \\
\end{array}\right] \quad
*
\left[\begin{array}{c}
    y_{11}&y_{12} \\
    y_{21}&y_{22} \\
    y_{31}&y_{32} \\
\end{array}\right] \quad
=
\left[\begin{array}{c}
    x_{11}y_{11}+x_{12}y_{21}+x_{13}y_{31}&x_{11}y_{12}+x_{12}y_{22}+x_{13}y_{32} \\
    x_{21}y_{11}+x_{22}y_{21}+x_{23}y_{31}&x_{21}y_{12}+x_{22}y_{22}+x_{23}y_{32} \\
\end{array}\right] \quad
$$

行列の転置
$$
\begin{align}
A &= \left(
    \begin{array}{ccc}
      1 & 2 & 3 \\
      4 & 5 & 6 \\
    \end{array}
  \right) \\
A^{\mathrm{T}} &= \left(
    \begin{array}{cc}
      1 & 4 \\
      2 & 5 \\
      3 & 6
    \end{array}
  \right) 
\end{align}
$$

In [ ]:
import numpy as np

# 行列の和
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[3,2,1], [6,5,4]])

print('a={}'.format(a))
print('-'*10)
print('b={}'.format(b))
print('-'*10)
print('a+b={}'.format(a+b))

a=[[1 2 3]
 [4 5 6]]
----------
b=[[3 2 1]
 [6 5 4]]
----------
a+b=[[ 4  4  4]
 [10 10 10]]


In [ ]:
# 行列の差
c = np.arange(6).reshape(2, 3)
d = np.arange(10, 16).reshape(2, 3)

print('c={}'.format(c))
print('-'*10)
print('d={}'.format(d))
print('-'*10)
print('c-d={}'.format(c-d))

c=[[0 1 2]
 [3 4 5]]
----------
d=[[10 11 12]
 [13 14 15]]
----------
c-d=[[-10 -10 -10]
 [-10 -10 -10]]


In [ ]:
# 数値と行列の積
x1 = np.arange(6).reshape(2,3)

print('x1=\n{}'.format(x1))
print('-'*10)
print('3*x1=\n{}'.format(3*x1))

x1=
[[0 1 2]
 [3 4 5]]
----------
3*x1=
[[ 0  3  6]
 [ 9 12 15]]


In [ ]:
# 行列と行列の積
x = np.arange(6).reshape(2, 3)
y = np.arange(3, 9).reshape(3, 2)

print('x={}'.format(x))
print('-'*10)
print('y={}'.format(y))
print('-'*10)
print('x*y={}'.format(np.dot(x, y)))

x=[[0 1 2]
 [3 4 5]]
----------
y=[[3 4]
 [5 6]
 [7 8]]
----------
x*y=[[19 22]
 [64 76]]


In [ ]:
# 行列の転置
a = np.array([1, 2, 3, 4, 5, 6]).reshape(2, -1)
print(a)
print('-'*10)
print(a.T)

[[1 2 3]
 [4 5 6]]
----------
[[1 4]
 [2 5]
 [3 6]]


逆行列 \
元行列(正方行列)との積は単位行列となるものは逆行列である。
$$
A^{-1}A=E \\
AA^{-1}=E
$$

逆行列の求め方
2*2の場合
$$
\begin{align}
&A = \left(
    \begin{array}{ccc}
      a & b \\
      c & d \\
     \end{array}
  \right) \\
&A^{-1} = \frac{1}{|A|} \
\left(
    \begin{array}{ccc}
      d & -b \\
      -c & a \\
     \end{array}
\right) \
= \frac{1}{ad-bc} \
\left(
    \begin{array}{ccc}
      d & -b \\
      -c & a \\
     \end{array}
\right) \\
\end{align}
$$

掃き出し法 \
余因子を用いる\
https://manabitimes.jp/math/1153

In [ ]:
a = np.arange(4).reshape(2,2)
inv_a = np.linalg.inv(a)
print(a)
print('-'*10)
print('aの逆行列は\n{}'.format(inv_a))
print('-'*10)
print('aとinv_aとの積は\n{}'.format(a.dot(inv_a)))

[[0 1]
 [2 3]]
----------
aの逆行列は
[[-1.5  0.5]
 [ 1.   0. ]]
----------
aとinv_aとの積は
[[1. 0.]
 [0. 1.]]


行列式detA,|A|
$$
\begin{align}
&A = \left(
    \begin{array}{ccc}
      a_{11} & a_{12} \\
      a_{21} & a_{22} \\
     \end{array}
  \right) \\
&|A|=a_{11}a_{22} - a_{12}a_{21} \\
\\
\\
&A = \left(
    \begin{array}{ccc}
      a_{11} & a_{12} & a_{13}\\
      a_{21} & a_{22} & a_{23}\\
      a_{31} & a_{32} & a_{33}\\
     \end{array}
  \right) \\
|A|=a_{11}a_{22}a_{33}+a_{21}a_{32}a_{13}+a_{31}a_{12}a_{23}
\\-a_{31}a_{22}a_{13}-a_{32}a_{23}a_{11}-a_{33}a_{21}a_{12}
\end{align}
$$

In [ ]:
a = np.arange(4).reshape(2,2)
det_a = np.linalg.det(a)
print(a)
print('-'*10)
print(det_a)

[[0 1]
 [2 3]]
----------
-2.0


単位ベクトル\
大きさ１のベクトル\
$$
x= \left(
    \begin{array}{ccc}
      x_1\\
      x_2\\
      ...\\
      x_n\\
     \end{array}
  \right) \\
$$
xを単位ベクトルにすると
$$
\frac{x}{|x|} \\
|x|=\sqrt{x_1^2+x_2^2+...+x_n^2}
$$

In [ ]:
a = np.array([3, 4])
norm_a = np.linalg.norm(a)
b = a / norm_a

print(a)
print('-'*10)
print(norm_a)
print('-'*10)
print(b)

[3 4]
----------
5.0
----------
[0.6 0.8]


### 固有値分解(正方行列)
固有値に着目した行列の分解である。
$$
A = VΛV^{-1}
$$
V：固有ベクトルを並べた行列\
Λ：対角成分は固有値の行列\
\
手順：

$$
\begin{align*}
&①|A-λE|=0
より固有値λを求める\\
&②(A-λE)\bar{v}=\bar{0}
より固有ベクトルvを求める\\
&③A = VΛV^{-1}
\end{align*}
$$


例：

$$
A = 
\left(
\begin{array}{ccc}
  2 & 1\\
  1 & 2\\
\end{array}
\right)
を固有値分解せよ
$$

$$
\begin{align*}
&①|A-λE|=0
より固有値λを求める\\
\end{align*}
$$

$$
\left|
\left(
\begin{array}{ccc}
2 & 1\\
1 & 2\\
\end{array}
\right)
-λ
\left(
\begin{array}{ccc}
1 & 0\\
0 & 1\\
\end{array}
\right)
\right|
=0
$$

$$
\left|
\left(
\begin{array}{ccc}
2 & 1\\
1 & 2\\
\end{array}
\right)
-
\left(
\begin{array}{ccc}
λ & 0\\
0 & λ\\
\end{array}
\right)
\right|
=0
$$

$$
\left|
\begin{array}{ccc}
2-λ & 1\\
1 & 2-λ\\
\end{array}
\right|
=0
$$

$$
(2-λ)^2-1=0
$$

$$
λ=3, λ=1
$$

$$
\begin{align*}
&②(A-λE)\bar{v}=\bar{0}
より固有ベクトルvを求める\\
\end{align*}
$$

$$
λ=3の時\\
\left(
\left(
\begin{array}{ccc}
2&1\\
1&2\\
\end{array}
\right)
-3
\left(
\begin{array}{ccc}
1&0\\
0&1\\
\end{array}
\right)
\right)
\left(
\begin{array}{ccc}
v_1\\
v_2\\
\end{array}
\right)
=
\bar{0}
$$

$$
\left(
\begin{array}{ccc}
-1&1\\
1&-1\\
\end{array}
\right)
\left(
\begin{array}{ccc}
v_1\\
v_2\\
\end{array}
\right)
=
\left(
\begin{array}{ccc}
0\\
0\\
\end{array}
\right)
$$

$$
-v_1+v_2=0\\
v_1-v_2=0\\
v_1=v_2=1\\
\bar{v}
=
\left(
\begin{array}{ccc}
1\\
1\\
\end{array}
\right)
$$

$$
λ=1の時\\
\left(
\left(
\begin{array}{ccc}
2&1\\
1&2\\
\end{array}
\right)
-1
\left(
\begin{array}{ccc}
1&0\\
0&1\\
\end{array}
\right)
\right)
\left(
\begin{array}{ccc}
v_1\\
v_2\\
\end{array}
\right)
=
\bar{0}
$$

$$
\left(
\begin{array}{ccc}
1&1\\
1&1\\
\end{array}
\right)
\left(
\begin{array}{ccc}
v_1\\
v_2\\
\end{array}
\right)
=
\left(
\begin{array}{ccc}
0\\
0\\
\end{array}
\right)
$$

$$
v_1+v_2=0\\
v_1=1\\
v_2=-1\\
\bar{v}
=
\left(
\begin{array}{ccc}
1\\
-1\\
\end{array}
\right)
$$

$$
\begin{align*}
&③A = VΛV^{-1}
\end{align*}
$$

$$
A=
\left(
\begin{array}{ccc}
1&1\\
1&-1\\
\end{array}
\right)
\left(
\begin{array}{ccc}
3&0\\
0&1\\
\end{array}
\right)
\left(
\begin{array}{ccc}
1&1\\
1&-1\\
\end{array}
\right)^{-1}
$$

$$
A=
\left(
\begin{array}{ccc}
1&1\\
1&-1\\
\end{array}
\right)
\left(
\begin{array}{ccc}
3&0\\
0&1\\
\end{array}
\right)
\left(
\begin{array}{ccc}
0.5&0.5\\
0.5&-0.5\\
\end{array}
\right)
$$

### 特異値分解（m＊n行列）
<img src='img/特異値分解.jpg' width=80%/>
https://qiita.com/kidaufo/items/0f3da4ca4e19dc0e987e
$$
A=UΣV^{-1}\\
A=UΣV^{T}\\
ここで  
V^{-1}=V^{T}
$$

手順：
$$
\begin{align*}
&①AA^{T}とA^{T}Aを求める\\
&②-①
\left|
AA^{T}-λE
\right|
=0
よりλを求める\\
&②-②
\left(
AA^{T}-λE
\right)
\bar{u}
=
\bar{0}
により左ベクトルuを求める\\
&③-①
\left|
A^{T}A-λE
\right|
=0
よりλを求める\\
&③-②
\left(
A^{T}A-λE
\right)
\bar{v}
=
\bar{0}
により右ベクトルvを求める\\
&④A=UΣV^{T}
=(u_1, u_2...)
\left(
\begin{array}{ccc}
σ_1&...&0\\
0&σ_2&..&0\\
..&..&..\\
\end{array}
\right)
(v_1,v_2...)^{T}\\
&・σ_i= \sqrt{λ}\\
&・σ_1>σ_2>σ_3..\\
&・u_i,v_iは単位ベクトル
\end{align*}
$$

例：
$$
A=
\left(
\begin{array}{ccc}
1&0&1\\
0&1&1\\
\end{array}
\right)
を特異値分解せよ
$$

$$
\begin{align*}
&①AA^{T}とA^{T}Aを求める\\
&A^T=
\left(
\begin{array}{ccc}
1&0\\
0&1\\
1&1\\
\end{array}
\right)\\
&AA^{T}=
\left(
\begin{array}{ccc}
2&1\\
1&2\\
\end{array}
\right)
&AA^{T}=
\left(
\begin{array}{ccc}
1&0&1\\
0&1&1\\
1&1&2\\
\end{array}
\right)
\end{align*}
$$

$$
\begin{align*}
&②-①
\left|
AA^{T}-λE
\right|
=0
よりλを求める\\
&λ=3,λ=1
\end{align*}
$$

$$
\begin{align*}
&②-②
\left(
AA^{T}-λE
\right)
\bar{u}
=
\bar{0}
により左ベクトルuを求める\\
&λ=3の時\\
&\bar{u}=
\left(
\begin{array}{ccc}
1/\sqrt{2}\\
1/\sqrt{2}\\
\end{array}
\right)\\
&λ=1の時\\
&\bar{u}=
\left(
\begin{array}{ccc}
1/\sqrt{2}\\
-1/\sqrt{2}\\
\end{array}
\right)
\end{align*}
$$

$$
\begin{align*}
&③-①
\left|
A^{T}A-λE
\right|
=0
よりλを求める\\
&λ=3,λ=1,λ=0
\end{align*}
$$

$$
\begin{align*}
&②-②
\left(
A^{T}A-λE
\right)
\bar{v}
=
\bar{0}
により左ベクトルuを求める\\
&λ=3の時\\
&\bar{v}=
\left(
\begin{array}{ccc}
\sqrt{1/6}\\
\sqrt{1/6}\\
\sqrt{2/3}\\
\end{array}
\right)\\
&λ=1の時\\
&\bar{v}=
\left(
\begin{array}{ccc}
\sqrt{1/2}\\
\sqrt{1/2}\\
0\\
\end{array}
\right)\\
&λ=0の時\\
&\bar{v}=
\left(
\begin{array}{ccc}
\sqrt{1/3}\\
\sqrt{1/3}\\
\sqrt{1/3}\\
\end{array}
\right)\\
\end{align*}
$$

$$
\begin{align*}
&④A=UΣV^{T}
=(u_1, u_2...)
\left(
\begin{array}{ccc}
σ_1&...&0\\
0&σ_2&..&0\\
..&..&..\\
\end{array}
\right)
(v_1,v_2...)^{T}\\
&A=
\left(
\begin{array}{ccc}
\sqrt{1/2}&\sqrt{1/2}\\
\sqrt{1/2}&\sqrt{-1/2}\\
\end{array}
\right)
\end{align*}
$$

$$
\begin{align*}
A=
\left(
\begin{array}{ccc}
\sqrt{1/2}&\sqrt{1/2}\\
\sqrt{1/2}&\sqrt{-1/2}\\
\end{array}
\right)
\left(
\begin{array}{ccc}
\sqrt{3}&0&0\\
0&1&0\\
\end{array}
\right)\\
\left(
\begin{array}{ccc}
\sqrt{1/6}&\sqrt{1/2}&\sqrt{-1/3}\\
\sqrt{1/6}&\sqrt{1/2}&\sqrt{-1/3}\\
\sqrt{4/6}&0&\sqrt{1/3}\\
\end{array}
\right)^T
\end{align*}
$$